FROM alpine:3.19

RUN apk add --no-cache bash iptables iproute2 iputils curl net-tools bind-tools

COPY start-spine.sh /usr/local/bin/start-spine.sh
RUN chmod +x /usr/local/bin/start-spine.sh

CMD ["/usr/local/bin/start-spine.sh"]
