global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'nexus-enterprise-nms'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'nexus-corp-web'
    static_configs:
      - targets: ['10.0.1.20:5000']
    metrics_path: '/health'

  - job_name: 'nexus-erp'
    static_configs:
      - targets: ['10.0.3.10:8000']
    metrics_path: '/health'

  - job_name: 'nexus-cloud-app'
    static_configs:
      - targets: ['172.16.0.20:8080']
    metrics_path: '/api/v1/health'

  - job_name: 'nexus-nac'
    static_configs:
      - targets: ['10.0.2.15:8100']
    metrics_path: '/health'
