[global]
   workgroup = NEXUS
   server string = Nexus Enterprise Active Directory Domain Controller (DC01)
   realm = NEXUS.INTERNAL
   security = user
   map to guest = Bad User
   dns proxy = no
   log file = /var/log/samba/log.%m
   max log size = 1000
   server role = standalone server
   passdb backend = tdbsam
   obey pam restrictions = yes
   unix password sync = yes
   passwd program = /usr/bin/passwd %u
   passwd chat = *Enter\snew\s*\spassword:* %n\n *Retype\snew\s*\spassword:* %n\n *password\supdated\ssuccessfully* .
   pam password change = yes

[netlogon]
   comment = Network Logon Service
   path = /var/lib/samba/sysvol/nexus.internal/scripts
   guest ok = yes
   read only = yes

[sysvol]
   comment = Active Directory SYSVOL Share
   path = /var/lib/samba/sysvol
   guest ok = yes
   read only = yes

[IT-Backups]
   comment = IT Engineering Backup & Deployment Scripts (RESTRICTED)
   path = /shared/it_backups
   browseable = yes
   guest ok = yes
   read only = yes

[HR-Public]
   comment = HR Department Shared Policies & Onboarding Guides
   path = /shared/hr_public
   browseable = yes
   guest ok = yes
   read only = yes
