[default]
exten => 1001,1,Dial(PJSIP/1001,30)
exten => 1001,2,Voicemail(1001@default,u)
exten => 1001,3,Hangup()
exten => 1002,1,Dial(PJSIP/1002,30)
exten => 1002,2,Voicemail(1002@default,u)
exten => 1002,3,Hangup()
exten => 1003,1,Dial(PJSIP/1003,30)
exten => 1003,2,Voicemail(1003@default,u)
exten => 1003,3,Hangup()
exten => 1004,1,Dial(PJSIP/1004,30)
exten => 1004,2,Voicemail(1004@default,u)
exten => 1004,3,Hangup()
; Conference bridge
exten => 9000,1,ConfBridge(nexus-board-room)
exten => 9000,2,Hangup()
